name: test action
run-name: ${{ github.actor }} is running tests
permissions:
    contents: read
    pages: read
    id-token: write

on: [pull_request, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v5
            - name: Install dependencies
              run: npm ci
            - name: Run lint and prettier
              run: npm run lint && npm run format:check
            - name: Run tests
              run: npm run test
            - name: Build Action
              run: npm run build
            - name: 'Az CLI login'
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
            - name: 'Run Azure Compliance Controls'
              uses: ./
              with:
                  subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
                  cydigConfigPath: ${{ github.workspace }}/src/cydigConfig.json
